@startuml uml
skinparam sequenceMessageAlign center
skinparam defaultFontSize 10
skinparam defaultFontName Arial
skinparam sequenceBoxBorderColor #0000FF
skinparam sequenceBoxBackgroundColor #99CCFF

title Client-server communication protocol
box #Teal
Actor User
entity ClientMain
participant View
participant Minimodel
box "Network" #Aqua
participant Client
queue CommandQueue
queue EventQueue
participant Server
end box
participant Controller
participant Model
entity ServerMain
end box


group #LightGrey "Communication Setup" :
    activate ServerMain
    ServerMain->Server: create RMIserver and SocketServer
        note over Server
            queue and thread
            setup + server run
        end note
    activate Server
    activate User
    User->ClientMain: choose connection and \ninterface via terminal
    activate ClientMain
    ClientMain->Client: uses abstract factory pattern \nto create a proper player
    activate Client
    note over Client
        queue and thread
        setup + view run
    end note
    Client->Server: binding or TCP handshake
    Server--> User: connection established
end group

group #LightGrey "Midgame Communication":
User->View: uses GUI or TUI interface
activate View
View->Minimodel: takes object needed to \ngenerate the command
Minimodel-->View: returns objects
note over View: generates command
View->Client: propagates command
!pragma teoz true
Client->EventQueue: puts command in queue
& Server->EventQueue: extracts commands from queue
==Remote method invocation or stream writing==
EventQueue --> View: return
Server->Controller: message executed passing model
Controller->Model: changes game state
Model-->Server: return
note over Model: generate event
Model->Server: propagates event
!pragma teoz true
Server->CommandQueue: puts event in queue
& Client->CommandQueue: extracts events from queue
CommandQueue-->Model: return
==Remote method invocation or stream writing==
Client->Minimodel: event executed passing minimodel
Minimodel->View: update view
View-->Client: return
View->User: displays changes

end group
@enduml
